[colors.primary]
background = "#0C0C0C" # darkness_6 - Matthew 27:45
foreground = "#C2AE93" # broken_bread_1 - Matthew 26:17,26

[colors.cursor]
text = "#0C0C0C"   # darkness_6 - Matthew 27:45
cursor = "#3AAB87" # water_of_life_2 - Revelation 22:1,17

[colors.selection]
background = "#3AAB87" # water_of_life_2 - Revelation 22:1,17
text = "#0C0C0C"       # darkness_6 - Matthew 27:45

[colors.normal]
black = "#484848"   # darkness_1 - Matthew 27:45
red = "#B83E46"     # poured_wine_1 - Matthew 26:27-29
green = "#838F46"   # gethsemane_oil_1 - Exodus 27:20; Matthew 26:36
yellow = "#DCAE3D"  # royal_sash_1 - Revelation 1:13
blue = "#6C9FBF"    # resurrection_morning_1 - Mark 16:2
magenta = "#8B476D" # thorned_veil_1 - Exodus 26:31; Matthew 27:51
cyan = "#3AAB87"    # water_of_life_2 - Revelation 22:1,17
white = "#C2AE93"   # broken_bread_1 - Matthew 26:17,26

[colors.bright]
black = "#484848"   # darkness_1 - Matthew 27:45
red = "#B83E46"     # poured_wine_1 - Matthew 26:27-29
green = "#838F46"   # gethsemane_oil_1 - Exodus 27:20; Matthew 26:36
yellow = "#DCAE3D"  # royal_sash_1 - Revelation 1:13
blue = "#6C9FBF"    # resurrection_morning_1 - Mark 16:2
magenta = "#8B476D" # thorned_veil_1 - Exodus 26:31; Matthew 27:51
cyan = "#3AAB87"    # water_of_life_2 - Revelation 22:1,17
white = "#C2AE93"   # broken_bread_1 - Matthew 26:17,26
