[colors.primary]
background = "#040B0A"
foreground = "#C2AE93"

[colors.cursor]
text = "#040B0A"
cursor = "#6C9FBF"

[colors.selection]
background = "#243342"
text = "CellForeground"

[colors.normal]
black = "#243342"
red = "#B83E46"
green = "#838F46"
yellow = "#DCAE3D"
blue = "#6C9FBF"
magenta = "#8B476D"
cyan = "#40BE96"
white = "#C2AE93"

[colors.bright]
black = "#243342"
red = "#B83E46"
green = "#838F46"
yellow = "#DCAE3D"
blue = "#6C9FBF"
magenta = "#8B476D"
cyan = "#40BE96"
white = "#C2AE93"
