background = #151515
foreground = #d2d2d2
selection-background = #3E4452
selection-foreground = #d2d2d2
cursor-color = #BAA0E8

palette = 0=#3E4452
palette = 1=#DD6E6B
palette = 2=#87E58E
palette = 3=#E8EDA2
palette = 4=#BAA0E8
palette = 5=#E48CC1
palette = 6=#A7DFEF
palette = 7=#d2d2d2

palette = 8=#3E4452
palette = 9=#DD6E6B
palette = 10=#87E58E
palette = 11=#E8EDA2
palette = 12=#BAA0E8
palette = 13=#E48CC1
palette = 14=#A7DFEF
palette = 15=#d2d2d2
