background = #040B0A
foreground = #C2AE93
selection-background = #243342
selection-foreground = #DCAE3D
cursor-color = #6C9FBF

palette = 0=#243342
palette = 1=#B83E46
palette = 2=#838F46
palette = 3=#DCAE3D
palette = 4=#6C9FBF
palette = 5=#8B476D
palette = 6=#40BE96
palette = 7=#C2AE93

palette = 8=#243342
palette = 9=#B83E46
palette = 10=#838F46
palette = 11=#DCAE3D
palette = 12=#6C9FBF
palette = 13=#8B476D
palette = 14=#40BE96
palette = 15=#C2AE93
