# darkness_6 - Matthew 27:45
background = #0C0C0C
# broken_bread_1 - Matthew 26:17,26
foreground = #C2AE93
# water_of_life_2 - Revelation 22:1,17
selection-background = #3AAB87
# darkness_6 - Matthew 27:45
selection-foreground = #0C0C0C
# water_of_life_2 - Revelation 22:1,17
cursor-color = #3AAB87

# darkness_1 - Matthew 27:45
palette = 0=#484848
# poured_wine_1 - Matthew 26:27-29
palette = 1=#B83E46
# gethsemane_oil_1 - Exodus 27:20; Matthew 26:36
palette = 2=#838F46
# royal_sash_1 - Revelation 1:13
palette = 3=#DCAE3D
# resurrection_morning_1 - Mark 16:2
palette = 4=#6C9FBF
# thorned_veil_1 - Exodus 26:31; Matthew 27:51
palette = 5=#8B476D
# water_of_life_2 - Revelation 22:1,17
palette = 6=#3AAB87
# broken_bread_1 - Matthew 26:17,26
palette = 7=#C2AE93

# Bright variants are bloat
# darkness_1 - Matthew 27:45
palette = 8=#484848
# poured_wine_1 - Matthew 26:27-29
palette = 9=#B83E46
# gethsemane_oil_1 - Exodus 27:20; Matthew 26:36
palette = 10=#838F46
# royal_sash_1 - Revelation 1:13
palette = 11=#DCAE3D
# resurrection_morning_1 - Mark 16:2
palette = 12=#6C9FBF
# thorned_veil_1 - Exodus 26:31; Matthew 27:51
palette = 13=#8B476D
# water_of_life_2 - Revelation 22:1,17
palette = 14=#3AAB87
# broken_bread_1 - Matthew 26:17,26
palette = 15=#C2AE93
