general {
    col.active_border = rgb(3AAB87) # water_of_life_2 - Revelation 22:1,17
    col.inactive_border = rgb(484848) # darkness_1 - Matthew 27:45
    border_size = 3
    gaps_in = 2
    gaps_out = 2
}

decoration {
    rounding = 0
}
