background #0C0C0C
foreground #C2AE93
cursor #6C9FBF
cursor_text_color #0C0C0C
selection_background #3C3C3C
selection_foreground none

# Normal
color0  #3C3C3C
color1  #B83E46
color2  #838F46
color3  #DCAE3D
color4  #6C9FBF
color5  #8B476D
color6  #40BE96
color7  #C2AE93

# Bright
color8  #3C3C3C
color9  #B83E46
color10 #838F46
color11 #DCAE3D
color12 #6C9FBF
color13 #8B476D
color14 #40BE96
color15 #C2AE93
