background #040B0A
foreground #C2AE93
cursor #6C9FBF
cursor_text_color #040B0A
selection_background #243342
selection_foreground none

# Normal
color0  #243342
color1  #B83E46
color2  #838F46
color3  #DCAE3D
color4  #6C9FBF
color5  #8B476D
color6  #40BE96
color7  #C2AE93

# Bright
color8  #243342
color9  #B83E46
color10 #838F46
color11 #DCAE3D
color12 #6C9FBF
color13 #8B476D
color14 #40BE96
color15 #C2AE93
