background #151515
foreground #d2d2d2
cursor #BAA0E8
cursor_text_color #151515
selection_background #3E4452
selection_foreground #d2d2d2

# Normal
color0  #3E4452
color1  #DD6E6B
color2  #87E58E
color3  #E8EDA2
color4  #BAA0E8
color5  #E48CC1
color6  #A7DFEF
color7  #d2d2d2

# Bright
color8  #3E4452
color9  #DD6E6B
color10 #87E58E
color11 #E8EDA2
color12 #BAA0E8
color13 #E48CC1
color14 #A7DFEF
color15 #d2d2d2
