# broken_bread_1 - Matthew 26:17,26
text-color=#C2AE93
# darkness_6 - Matthew 27:45
background-color=#0C0C0C
width=420
height=110
padding=10
border-size=3
border-radius=0
font=Liberation Sans 11
anchor=top-right
outer-margin=20
default-timeout=5000
max-icon-size=32

# water_of_life_2 - Revelation 22:1,17
border-color=#3AAB87

[app-name=Spotify]
invisible=1

[mode=do-not-disturb]
invisible=true

[mode=do-not-disturb app-name=notify-send]
invisible=false

# darkness_1 - Matthew 27:45
[urgency=low]
border-color=#484848
default-timeout=3000

# royal_sash_1 - Revelation 1:13
[urgency=normal summary~="[Ww]arning|[Aa]lert|[Aa]ttention"]
border-color=#DCAE3D

# poured_wine_1 - Matthew 26:27-29
[urgency=critical]
border-color=#B83E46
default-timeout=0
